#!/bin/zsh
set -euo pipefail

ROOT="${0:A:h:h}"
APP_SOURCE="${ROOT}/Sources/WorkPulseMenuBar/WorkPulseMenuBarApp.swift"
NOTCH_SOURCE="${ROOT}/Sources/WorkPulseMenuBar/NotchOverlayController.swift"
NOTIFICATION_SOURCE="${ROOT}/Sources/WorkPulseMenuBar/NotificationCoordinator.swift"
TASK_READER_SOURCE="${ROOT}/Sources/WorkPulseCore/CodexTaskReader.swift"
SNAPSHOT_STORE_SOURCE="${ROOT}/Sources/WorkPulseCore/SnapshotStore.swift"
WIDGET_SOURCE="${ROOT}/WidgetExtension/WorkPulseWidget.swift"
PACKAGE_SCRIPT="${ROOT}/scripts/package_app.sh"
FULL_PRODUCT_SCRIPT="${ROOT}/scripts/build_full_product.sh"
WIDGET_RUNTIME_SCRIPT="${ROOT}/scripts/verify_widget_runtime.sh"

assert_current_codesign_entitlements_interface() {
  if rg -q --fixed-strings -- '--entitlements :-' \
      "${FULL_PRODUCT_SCRIPT}" \
      "${ROOT}/scripts/install_signed_product.sh"; then
    print -u2 "FAIL: 签名权限读取仍使用已废弃的 --entitlements :- 写法"
    exit 1
  fi
  print "PASS: 签名权限读取使用当前 codesign --entitlements - 接口"
}

assert_contains() {
  local file="$1"
  local pattern="$2"
  local label="$3"
  if ! rg -q --fixed-strings "${pattern}" "${file}"; then
    print -u2 "FAIL: ${label}"
    exit 1
  fi
  print "PASS: ${label}"
}

assert_absent() {
  local file="$1"
  local pattern="$2"
  local label="$3"
  if rg -q --fixed-strings "${pattern}" "${file}"; then
    print -u2 "FAIL: ${label}"
    exit 1
  fi
  print "PASS: ${label}"
}

assert_current_codesign_entitlements_interface
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'env -i' "签名安装不会把代理或 QA 环境泄漏给 WorkPulse"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'launch_installed_app' "安装与回滚共用干净启动入口"

assert_absent "${APP_SOURCE}" 'Window("WorkPulse", id: "main")' "没有独立 Dashboard scene"
assert_contains "${ROOT}/AppBundle/Info.plist" '<true/>' "本地宿主为 LSUIElement"
assert_contains "${ROOT}/Xcode/HostInfo.plist" '<key>LSUIElement</key>' "Xcode 宿主声明后台形态"
assert_contains "${ROOT}/Xcode/HostInfo.plist" '<key>WorkPulseWidgetRuntimeEnabled</key>' "团队签名构建开启 Widget 运行写入"
assert_contains "${ROOT}/AppBundle/Info.plist" '<key>WorkPulseWidgetRuntimeEnabled</key>' "ad-hoc 构建声明 Widget 降级状态"
assert_contains "${ROOT}/project.yml" 'type: app-extension' "存在真实 Widget Extension target"
assert_contains "${ROOT}/WorkPulse.xcodeproj/project.pbxproj" 'com.apple.product-type.app-extension' "Xcode project 已生成 Widget target"
assert_contains "${ROOT}/WorkPulse.xcodeproj/project.pbxproj" 'Embed Foundation Extensions' "宿主会嵌入 Widget appex"
assert_contains "${ROOT}/Xcode/WidgetInfo.plist" 'com.apple.widgetkit-extension' "Widget extension point 正确"
assert_contains "${ROOT}/Xcode/WorkPulse.entitlements" '$(WORKPULSE_APP_GROUP)' "宿主 App Group 使用团队作用域配置"
assert_contains "${ROOT}/Xcode/WorkPulseWidget.entitlements" '$(WORKPULSE_APP_GROUP)' "Widget App Group 使用团队作用域配置"
assert_contains "${ROOT}/project.yml" 'WORKPULSE_APP_GROUP: "$(DEVELOPMENT_TEAM).com.workpulse.shared"' "Xcode 构建从 Development Team 派生共享容器"

PROJECT_COUNT="$(find "${ROOT}" -name '*.xcodeproj' -type d -prune -print | wc -l | tr -d ' ')"
[[ "${PROJECT_COUNT}" == 1 ]] || { print -u2 "FAIL: 仓库必须只有一个正式 Xcode project"; exit 1; }
print "PASS: 仓库只有一个正式 Xcode project"

CONTROL_SECTION_COUNT="$(rg -c 'controlSection\("' "${APP_SOURCE}")"
[[ "${CONTROL_SECTION_COUNT}" == 5 ]] || { print -u2 "FAIL: 控制中心一级设置应收敛为 5 组"; exit 1; }
print "PASS: 控制中心一级设置收敛为 5 组"
assert_absent "${APP_SOURCE}" 'Text("本机开发版")' "控制中心不展示无操作价值的商业化宣传卡"
assert_contains "${APP_SOURCE}" '添加：桌面右键 → 编辑小组件 → 搜索 WorkPulse' "控制中心明确说明如何从组件库添加 WorkPulse"
assert_contains "${APP_SOURCE}" '重新读取 Codex 额度并更新已经添加到桌面的 WorkPulse 小组件；不会自动添加新组件' "组件刷新按钮读取真实额度且不冒充自动安装"

for widget in WorkPulseQuotaWidget WorkPulsePinnedRoutineWidget WorkPulseQuickViewWidget WorkPulseDailyOverviewWidget; do
  assert_contains "${WIDGET_SOURCE}" "${widget}()" "WidgetBundle 包含 ${widget}"
done
assert_contains "${PACKAGE_SCRIPT}" 'WorkPulseWidgetCompile' "本地包会编译 Widget executable"
assert_contains "${PACKAGE_SCRIPT}" 'WorkPulseWidget.appex' "本地包会嵌入 Widget Extension"
assert_contains "${PACKAGE_SCRIPT}" 'WorkPulseWidget.entitlements' "Widget Extension 使用独立签名权限"
assert_contains "${PACKAGE_SCRIPT}" 'WorkPulse.entitlements' "宿主使用 App Group 签名权限"
assert_contains "${PACKAGE_SCRIPT}" 'LOCAL_APP_GROUP="group.com.workpulse.prototype"' "ad-hoc 本机包显式物化本地 App Group"

assert_contains "${NOTCH_SOURCE}" 'case resident' "刘海层包含常驻态"
assert_contains "${NOTCH_SOURCE}" 'case alert' "刘海层包含一次性提醒态"
assert_contains "${NOTCH_SOURCE}" 'case expanded' "刘海层包含主动展开态"
assert_contains "${NOTCH_SOURCE}" 'NSPanel' "刘海层使用原生 NSPanel"
assert_contains "${NOTCH_SOURCE}" 'screen.safeAreaInsets.top > 0' "可识别有刘海与无刘海屏幕"
assert_contains "${NOTCH_SOURCE}" 'CGDisplayIsBuiltin(displayID)' "顶部层可识别 Mac 内建屏幕"
assert_contains "${NOTCH_SOURCE}" 'DisplayPlacementPolicy.preferredDisplayID' "多屏位置使用固定策略而非跟随鼠标"
assert_contains "${NOTCH_SOURCE}" 'contentTopInset = isNotchScreen ? screen.safeAreaInsets.top : 0' "刘海屏内容从物理刘海下缘开始"
assert_contains "${NOTCH_SOURCE}" 'NotchIslandShape' "刘海屏使用融合式岛形而非普通悬浮胶囊"
assert_contains "${NOTCH_SOURCE}" 'event.keyCode == 53' "Expanded 支持 Esc 关闭"
assert_contains "${NOTCH_SOURCE}" 'setAlertHovering' "Alert hover 会暂停自动收回"
assert_contains "${NOTCH_SOURCE}" 'setExpandedHovering' "Expanded 在鼠标悬停时保持展开"
assert_contains "${NOTCH_SOURCE}" 'expandedKeyboardInteractionActive' "Expanded 键盘交互期间不会因鼠标离开而收回"
assert_contains "${NOTCH_SOURCE}" 'NSWorkspace.shared.isVoiceOverEnabled' "VoiceOver 运行时顶部层不会自动打断交互"
assert_contains "${NOTCH_SOURCE}" 'NSWorkspace.shared.isSwitchControlEnabled' "Switch Control 运行时顶部层不会自动打断交互"
assert_contains "${NOTCH_SOURCE}" 'case .alert:' "点击 Alert 会进入顶部 Expanded，而不是打开独立页面"
assert_contains "${NOTCH_SOURCE}" 'case snoozeEvent(UUID)' "顶部事件详情提供本地稍后动作"
assert_contains "${NOTCH_SOURCE}" 'case removeEvent(UUID)' "顶部事件详情提供本机移除动作"
assert_contains "${NOTCH_SOURCE}" 'panel.makeKeyAndOrderFront(nil)' "主动展开时顶部层可获得键盘焦点"
assert_contains "${NOTCH_SOURCE}" 'CGSSessionScreenIsLocked' "锁屏时顶部层不会冒充已投递"
assert_contains "${NOTCH_SOURCE}" 'return panel.isVisible && screen.frame.intersects(panel.frame)' "顶部提醒仅在实际可见时报告成功"

assert_contains "${NOTIFICATION_SOURCE}" 'UNUserNotificationCenterDelegate' "系统通知 delegate 已实现"
assert_contains "${NOTIFICATION_SOURCE}" 'requestAuthorization' "通知授权由用户显式触发"
assert_contains "${NOTIFICATION_SOURCE}" 'WORKPULSE_NEEDS_YOU' "通知 action category 已注册"
assert_contains "${NOTIFICATION_SOURCE}" 'deepLink' "通知点击可回流 WorkPulse route"
assert_contains "${NOTIFICATION_SOURCE}" 'WorkPulse 需要你的处理' "生产通知使用固定 generic title"
assert_contains "${NOTIFICATION_SOURCE}" 'workpulse://event/' "生产通知只能回流规范化 event UUID"
assert_contains "${NOTIFICATION_SOURCE}" 'WORKPULSE_QUOTA' "实时低额度提醒使用独立通知类别"
assert_contains "${NOTIFICATION_SOURCE}" 'workpulse://usage' "额度通知回流额度表面"
assert_contains "${NOTIFICATION_SOURCE}" 'WORKPULSE_TASK_TERMINAL' "任务完成、取消、失败和中止使用独立通知类别"
assert_contains "${NOTIFICATION_SOURCE}" 'case .completed: "Codex 任务已完成"' "任务系统通知标题始终使用 generic 文案"
assert_contains "${NOTIFICATION_SOURCE}" 'removeLegacyTaskNotificationsIfNeeded' "升级后清理可能含旧任务名的历史通知"
assert_contains "${NOTIFICATION_SOURCE}" 'scheduleTaskTerminalAlert' "明确的任务终态可在顶部不可达时调度系统通知"
assert_contains "${NOTIFICATION_SOURCE}" 'workpulse://task/' "任务终态通知回流具体任务结果而非泛化 Inbox"
assert_contains "${APP_SOURCE}" 'expandedContent: expandedContent' "单任务终态 Alert 点击后展开具体任务结果"
assert_contains "${NOTIFICATION_SOURCE}" 'actionIdentifier == UNNotificationDefaultActionIdentifier || actionIdentifier == "OPEN"' "只有默认点击和明确查看动作会打开通知路由"
assert_absent "${NOTIFICATION_SOURCE}" 'UNNotificationAction(identifier: "LATER"' "系统通知不提供尚未实现可靠重投的稍后动作"
assert_contains "${APP_SOURCE}" 'workpulse.lastNotificationOpenReceipt' "通知点击会持久化 request/action/route/result 回执"
assert_contains "${APP_SOURCE}" 'workpulse.recentTaskTerminalResults' "具体任务结果只保存在本机并在点击后按隐私偏好恢复"
assert_contains "${APP_SOURCE}" 'displayName: exposesTaskNames ? compactTaskName' "未授权显示时不持久化任务名称"
assert_contains "${APP_SOURCE}" 'scrubPersistedTaskNames()' "开启隐私或撤销名称授权时清除已缓存任务名"
assert_contains "${APP_SOURCE}" 'if privacyMode || !showTaskNamesInNotch' "宿主启动时重新执行持久化任务名隐私不变式"
assert_contains "${NOTIFICATION_SOURCE}" 'cleanupGroup.notify(queue: .main)' "只在旧任务通知清理回调完成后写入迁移标记"
assert_contains "${APP_SOURCE}" '上次点击已回流' "控制中心显示最近一次通知点击回流状态"
assert_contains "${NOTIFICATION_SOURCE}" 'workpulse://notification-preview' "通知预览点击具有可验证的专用回流路由"
assert_contains "${APP_SOURCE}" 'Text("跟随系统").tag(ThemePreference.system)' "外观支持跟随系统"
assert_contains "${APP_SOURCE}" 'Text("浅色").tag(ThemePreference.light)' "外观支持浅色"
assert_contains "${APP_SOURCE}" 'Text("深色").tag(ThemePreference.dark)' "外观支持深色"
assert_contains "${APP_SOURCE}" 'ForEach(AccentPreference.allCases' "用户可选择预设强调色"
assert_contains "${APP_SOURCE}" 'Image("WorkPulseLogo")' "菜单栏控制中心使用 WorkPulse 品牌标识"
assert_contains "${APP_SOURCE}" 'startBackgroundServices()' "宿主启动后台额度刷新"
assert_contains "${APP_SOURCE}" 'Task.sleep(for: .seconds(240))' "额度按四分钟周期刷新"
assert_contains "${APP_SOURCE}" 'return activeCodexTasks.isEmpty ? 10 : 5' "用户活跃时 Codex 任务按五至十秒刷新"
assert_contains "${APP_SOURCE}" 'return 120' "锁屏时任务监测退避到两分钟"
assert_contains "${APP_SOURCE}" 'sessionDidBecomeActiveNotification' "解锁会立即刷新任务状态"
assert_contains "${APP_SOURCE}" 'previousTaskCount != tasks.count || previousTaskState != .live' "Widget 只在可见任务摘要变化时刷新"
assert_contains "${APP_SOURCE}" 'NSWorkspace.didWakeNotification' "Mac 唤醒后刷新额度"
assert_contains "${APP_SOURCE}" 'ForEach(model.rateLimitBuckets)' "菜单栏展示全部额度窗口"
assert_contains "${APP_SOURCE}" 'selectQuotaBucket' "用户可选择 Widget 使用的额度窗口"
assert_contains "${APP_SOURCE}" 'case .usage:' "Widget 额度链接有独立回流路由"
assert_contains "${APP_SOURCE}" 'showQuotaStatusAlert()' "Widget 额度回流不会被运行任务抢占"
assert_contains "${APP_SOURCE}" 'title: notchResidentTitle' "刘海常驻使用统一信息优先级"
assert_contains "${APP_SOURCE}" 'private var notchResidentTitle: String {' "Resident 定义了稳定主信息"
assert_contains "${APP_SOURCE}" 'notchQuotaTitle' "Resident 始终保留剩余额度"
assert_contains "${APP_SOURCE}" 'return "\(notchQuotaResetLabel) · ● \(activeCodexTasks.count)"' "Resident 以次级计数同时显示运行任务"
assert_contains "${APP_SOURCE}" 'additionalBuckets + taskRows' "主动展开同时显示额度与运行任务"
assert_contains "${APP_SOURCE}" 'CodexRunningTaskReader.terminalOutcome(for: disappeared)' "任务只有存在明确终态证据才会触发提醒"
assert_contains "${APP_SOURCE}" 'showTaskTerminalAlert' "任务完成、取消、失败和中止使用不同提醒"
assert_contains "${APP_SOURCE}" 'showTaskNamesInNotch' "任务名称显示使用独立用户偏好"
assert_contains "${APP_SOURCE}" 'PresentationPrivacyPolicy.exposesUserTitle' "隐私模式会硬性覆盖标题显示偏好"
assert_contains "${APP_SOURCE}" 'object(forKey: "workpulse.privacy") == nil' "新安装默认开启隐私模式"
assert_contains "${APP_SOURCE}" 'guard !privacyMode else { return }' "隐私模式禁止通过临时动作显示任务名称"
assert_contains "${APP_SOURCE}" 'let mayShowTaskNames = !privacyMode' "隐私模式硬性覆盖已存在的临时名称状态"
assert_contains "${APP_SOURCE}" 'Task.sleep(for: .seconds(10))' "临时任务名称会自动恢复隐藏"
assert_contains "${APP_SOURCE}" 'topAlertsEnabled' "一次性顶部提醒使用独立偏好"
assert_contains "${APP_SOURCE}" 'notificationFallbackEnabled' "系统通知兜底使用独立偏好"
assert_contains "${APP_SOURCE}" 'WORKPULSE_QA_NOTIFICATION_PREVIEW' "签名宿主可执行隔离的通知送达验收"
assert_contains "${APP_SOURCE}" 'WORKPULSE_QA_TASK_NOTIFICATION_PREVIEW' "签名宿主可执行隔离的任务终态点击回流验收"
assert_contains "${APP_SOURCE}" 'displayName: nil' "任务终态 QA 通知不持久化任务名"
assert_contains "${NOTIFICATION_SOURCE}" 'func diagnosticSnapshot() async' "通知验收可区分授权、横幅、声音和 delivered 状态"
assert_contains "${APP_SOURCE}" '桌面组件同步失败' "Widget 快照错误会在菜单栏中显示"
assert_contains "${APP_SOURCE}" '桌面组件已同步' "Widget 快照成功状态会在菜单栏中显示"
assert_contains "${APP_SOURCE}" 'guard hasCompletedInitialQuotaAttempt else { return }' "首次额度读取完成前不会用空快照覆盖已有 Widget"
assert_contains "${SNAPSHOT_STORE_SOURCE}" 'quarantineCorruptSnapshot()' "损坏的 Widget 快照会保留诊断副本并由宿主自愈"
assert_contains "${APP_SOURCE}" '桌面组件等待 Apple Development 团队签名' "ad-hoc 宿主不会反复请求无权访问的 App Group"
assert_contains "${APP_SOURCE}" 'approvedRoutineTitle: nil' "Widget 永不写入用户自定义固定入口名称"
assert_contains "${APP_SOURCE}" 'hasValidPinnedTarget: validTargetURL != nil' "Widget 固定入口状态来自有效 HTTPS 目标"
assert_contains "${APP_SOURCE}" '.accessibilityValue(selected ? "已选择" : "未选择")' "额度窗口向 VoiceOver 暴露选中状态"
assert_contains "${APP_SOURCE}" 'environment.keys.contains(where: { $0.hasPrefix("WORKPULSE_QA_") })' "任何 QA 场景都不会向系统 Widget 外发模拟状态"
assert_contains "${WIDGET_SOURCE}" 'Text("非实时")' "Widget Gallery 额度预览明确标记非实时"
assert_absent "${WIDGET_SOURCE}" 'fresh ? "实时"' "Widget 不把周期快照冒充为实时数据流"
assert_contains "${WIDGET_SOURCE}" '"组件库预览 · 非实时"' "Widget Gallery 固定入口明确标记为示例"
assert_contains "${WIDGET_SOURCE}" 'snapshot.hasValidPinnedTarget' "Widget 不会把空或无效固定入口冒充为可打开目标"
assert_contains "${WIDGET_SOURCE}" '.widgetURL(URL(string: "workpulse://usage"))' "Widget 错误与空状态可点按进入恢复路由"
assert_contains "${WIDGET_SOURCE}" 'workpulse://routine/setup' "固定入口 Widget 错误态进入对应设置恢复路由"
assert_contains "${WIDGET_SOURCE}" 'dynamicTypeSize.isAccessibilitySize' "Widget 为大字号提供自适应信息布局"
assert_contains "${WIDGET_SOURCE}" 'entries.append(WorkPulseWidgetEntry(date: date, state: entry.state))' "Widget 会按 freshness 边界切换到过期状态"
assert_contains "${WIDGET_SOURCE}" 'return quota.resetsAt.map { date < $0 } ?? true' "Widget 在额度重置边界后不会继续突出旧百分比"
assert_contains "${WIDGET_SOURCE}" 'Array(Set((' "Widget 时间线对重复 freshness/reset 边界去重"
assert_contains "${WIDGET_SOURCE}" '.containerBackgroundRemovable(false)' "Widget 保留主题背景，避免系统着色后出现白字浅底"
assert_contains "${WIDGET_SOURCE}" '.supportedFamilies([.systemMedium])' "中型 Widget 已提供真实支持数据组合"
assert_contains "${WIDGET_SOURCE}" '.supportedFamilies([.systemLarge])' "大型 Widget 已提供真实今日概览"
assert_absent "${WIDGET_SOURCE}" 'WorkPulseNowNextWidget()' "组件库不发布未连接的 Needs You 组合"
assert_absent "${WIDGET_SOURCE}" 'WorkPulseDailyBriefWidget()' "组件库不发布虚构 Daily Brief"
assert_absent "${WIDGET_SOURCE}" '等待每日 Brief' "今日概览空态不冒充 Daily Brief 数据源"
assert_absent "${WIDGET_SOURCE}" 'Brief 不可用' "今日概览错误态使用真实能力名称"
assert_contains "${APP_SOURCE}" 'object(forKey: "workpulse.overlayEnabled") == nil' "首次启动默认开启核心顶部常驻状态"
assert_contains "${NOTCH_SOURCE}" 'override var canBecomeKey: Bool { true }' "主动展开层可取得键盘焦点"
assert_contains "${NOTCH_SOURCE}" 'setAlertKeyboardInteracting' "Full Keyboard Access 交互会暂停 Alert 倒计时"
assert_contains "${NOTCH_SOURCE}" 'colorSchemeContrast == .increased' "顶部表面响应 Increase Contrast"
assert_contains "${NOTCH_SOURCE}" 'setAccessibilityTextLayout(dynamicTypeSize.isAccessibilitySize)' "顶部表面按 Large Text 重新计算 panel 尺寸"
assert_contains "${NOTCH_SOURCE}" 'Task.sleep(for: .seconds(15))' "Expanded 键盘保护可续期且不会永久阻止收回"
assert_contains "${NOTCH_SOURCE}" 'isNotchScreen || isDarkSurface' "内置刘海灵动岛始终使用深色融合外壳"
assert_contains "${TASK_READER_SOURCE}" 'SQLITE_OPEN_READONLY' "Codex 任务数据库只读打开"
assert_contains "${TASK_READER_SOURCE}" 'title, cwd' "Codex 任务名优先使用任务标题"
assert_contains "${TASK_READER_SOURCE}" "NOT LIKE '%subagent%'" "内部子智能体任务不混入用户刘海状态"
assert_contains "${TASK_READER_SOURCE}" 'object["type"] as? String == "event_msg"' "任务监测只解析生命周期事件"
assert_contains "${TASK_READER_SOURCE}" '"task_started"' "任务监测识别开始边界"
assert_contains "${TASK_READER_SOURCE}" '"task_complete"' "任务监测识别完成边界"
assert_contains "${TASK_READER_SOURCE}" 'CodexTaskLifecycleCache' "任务监测缓存既有生命周期，避免每轮重复扫描大型 rollout"
assert_contains "${TASK_READER_SOURCE}" 'incrementalLowerBound' "任务监测在初次识别后只增量检查新增尾部"
assert_contains "${APP_SOURCE}" 'formattedResetTime' "刘海重置时间按今天、星期或日期紧凑显示"
assert_contains "${APP_SOURCE}" 'QuotaAlertPolicy.candidates' "低额度提醒按额度周期去重"
assert_contains "${APP_SOURCE}" 'previousRemainingByCycle: quotaPreviousRemainingByCycle' "低额度只在阈值跨越时触发"
assert_contains "${APP_SOURCE}" 'formattedResetTime(candidate.resetsAt)' "额度提醒包含下次重置时间"
assert_contains "${APP_SOURCE}" 'compactWindowLabel(candidate.windowDurationMinutes)' "额度提醒包含对应窗口身份"
assert_contains "${APP_SOURCE}" 'return "\(sourceName) 额度需更新"' "过期额度不继续突出精确百分比"
assert_contains "${APP_SOURCE}" 'Picker("低额度提醒"' "低额度提醒阈值可由用户关闭或调整"
assert_contains "${FULL_PRODUCT_SCRIPT}" '"${LSREGISTER}" -u "${APP}"' "团队签名构建结束后注销 DerivedData 宿主"
assert_contains "${FULL_PRODUCT_SCRIPT}" 'pluginkit -r "${APP}/Contents/PlugIns/WorkPulseWidget.appex"' "团队签名构建结束后注销 DerivedData Widget"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'OLD_WIDGET_EXECUTABLE' "升级前会停止旧 Widget 扩展进程"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'pluginkit -r "${OLD_WIDGET_BUNDLE}"' "升级前先注销旧 Widget 防止系统立即重启"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'pluginkit -r "${BACKUP}/Contents/PlugIns/WorkPulseWidget.appex"' "移动旧版备份后再次清理 Widget 注册"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'pluginkit -r "${failed_app}/Contents/PlugIns/WorkPulseWidget.appex"' "失败副本不会残留 Widget 注册"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'cleanup_and_rollback' "签名安装失败会自动回滚上一版"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'OLD_HOST_WAS_RUNNING == 1' "替换前中止会重启此前运行的旧宿主"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'WORKPULSE_INSTALL_TEST_FAIL_AFTER_OPEN' "安装器可故障注入验证启动后回滚"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'failed_host_pids' "启动后回滚会先终止失败的新宿主"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'stubborn_host_pids' "失败宿主不响应 TERM 时会强制结束并确认归零"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'restored_host_count' "回滚后必须恰好一个旧宿主实例"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'Host 与 Widget 的 TeamIdentifier 不一致' "安装前拒绝 Host 与 Widget 团队身份不一致"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'Host 与 Widget 的 App Group 不一致' "安装前拒绝 Host 与 Widget App Group 不一致"
assert_contains "${ROOT}/scripts/install_signed_product.sh" '安装后 Host binary 与签名归档不一致' "安装后验证 Host 与签名归档同源"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'verify_widget_runtime.sh' "安装后自动执行完整 Widget runtime 验收"
assert_contains "${ROOT}/scripts/install_signed_product.sh" 'pluginkit -a' "安装后会显式登记新 Widget 扩展"
assert_contains "${WIDGET_RUNTIME_SCRIPT}" 'PLUGIN_COUNT=' "Widget 运行验收会拒绝重复 PlugInKit 记录"

plutil -lint \
  "${ROOT}/AppBundle/Info.plist" \
  "${ROOT}/Xcode/HostInfo.plist" \
  "${ROOT}/Xcode/WidgetInfo.plist" \
  "${ROOT}/Xcode/WorkPulse.entitlements" \
  "${ROOT}/Xcode/WorkPulseWidget.entitlements"

print "WorkPulse system-surface verification passed."
